on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: 'job to say hello'
    steps:
      - name: 'hello world action step'
        id: hello
        uses: jonstout/hello-world-docker-action
      - name: 'echo stuff'
        run: echo "hahahahaha"
